import { spawn as spawnProcess } from "node:child_process"
import { writeFile, mkdir, rm, access } from "node:fs/promises"
import path from "node:path"
import { eq } from "drizzle-orm"
import { db, clients, clientConfig, managedContainers } from "@/lib/db"
import { getDocker, MANAGED_LABEL } from "@/lib/docker"
import type { Client, ClientConfig } from "@/lib/db/schema"

const CLIENTS_DIR = process.env.CLIENTS_DIR || "/srv/clients"
const ESNACK_REPO = "https://github.com/klinkragency/e-snack.git"

export type DeployEvent =
  | { type: "phase"; phase: string; message: string }
  | { type: "log"; message: string }
  | { type: "error"; message: string }
  | { type: "done"; publicUrl: string; composeProject: string }

/**
 * Streams lines of stdout/stderr as they arrive. Resolves to exit code.
 * No shell is used — args array is passed as-is, no injection risk even
 * with user-provided slugs/names.
 */
function runBinStream(
  cmd: string,
  args: string[],
  opts: { cwd?: string; env?: Record<string, string>; onLine: (line: string) => void } = { onLine: () => {} }
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawnProcess(cmd, args, {
      cwd: opts.cwd,
      env: { ...process.env, ...opts.env },
      shell: false,
    })
    let stderrTail = ""
    const emitChunk = (buf: Buffer | string) => {
      const str = buf.toString()
      str.split("\n").forEach((line) => {
        if (line.length > 0) opts.onLine(line)
      })
    }
    child.stdout?.on("data", emitChunk)
    child.stderr?.on("data", (b: Buffer) => {
      stderrTail += b.toString()
      emitChunk(b)
    })
    child.on("error", reject)
    child.on("close", (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} exit ${code}: ${stderrTail.slice(-400)}`))
    })
  })
}

function buildEnvFile(client: Client, config: ClientConfig, publicUrl: string): string {
  return [
    `# Generated by Klinkragency Dashboard at ${new Date().toISOString()}`,
    `DOMAIN=localhost`,
    `PUBLIC_URL=${publicUrl}`,
    `ALLOWED_ORIGIN=${publicUrl}`,
    `COOKIE_DOMAIN=`,
    `POSTGRES_USER=esnack`,
    `POSTGRES_PASSWORD=${config.postgresPassword}`,
    `POSTGRES_DB=esnack_db`,
    `JWT_SECRET=${config.jwtSecret}`,
    `COOKIE_SECRET=${config.cookieSecret}`,
    `BACKEND_URL=http://api:8080`,
    `INITIAL_ADMIN_EMAIL=${config.initialAdminEmail}`,
    `INITIAL_ADMIN_PASSWORD=${config.initialAdminPassword}`,
    `INITIAL_ADMIN_NAME=${config.initialAdminName}`,
    `INITIAL_RESTAURANT_NAME=${config.initialRestaurantName}`,
    `INITIAL_RESTAURANT_SLUG=${config.initialRestaurantSlug}`,
    `EMAIL_FROM_ADDRESS=${config.emailFromAddress}`,
    `EMAIL_FROM=${config.emailFromAddress}`,
    `EMAIL_FROM_NAME=${client.name}`,
    `EMAIL_PROVIDER=resend`,
    `EMAIL_API_KEY=${config.resendApiKey ?? ""}`,
    `RESEND_API_KEY=${config.resendApiKey ?? ""}`,
    `MOLLIE_API_KEY=${config.mollieApiKey ?? ""}`,
    `MINIO_ENDPOINT=`,
    `MINIO_ACCESS_KEY=`,
    `MINIO_SECRET_KEY=`,
    `MINIO_BUCKET=uploads`,
    `MINIO_USE_SSL=false`,
    `MINIO_PUBLIC_URL=`,
    `MINIO_ROOT_USER=minio`,
    `MINIO_ROOT_PASSWORD=${config.minioRootPassword}`,
    `GOOGLE_CLIENT_ID=`,
    `NEXT_PUBLIC_GOOGLE_CLIENT_ID=`,
    `OPENAI_API_KEY=`,
    `NEXT_PUBLIC_POSTHOG_KEY=`,
    `NEXT_PUBLIC_POSTHOG_HOST=`,
    `POSTHOG_PERSONAL_API_KEY=`,
    `POSTHOG_PROJECT_ID=`,
    `NEXT_PUBLIC_GOOGLE_OAUTH_ENABLED=false`,
    `NEXT_PUBLIC_APPLE_OAUTH_ENABLED=false`,
    `NEXT_PUBLIC_AI_IMPORT_ENABLED=false`,
    ``,
  ].join("\n")
}

/**
 * Surgical overrides to e-snack's upstream compose:
 * - unbinds postgres host port (would collide with dashboard's own pg)
 * - hides caddy behind a never-enabled profile (we use ngrok + host Caddy)
 */
function buildOverrideCompose(): string {
  return [
    "services:",
    "  postgres:",
    "    ports: !reset []",
    "  caddy:",
    '    profiles: ["disabled-by-dashboard"]',
    "",
  ].join("\n")
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

/**
 * Deploys a client instance, yielding progress events as it runs.
 * Consumers (e.g. SSE route) enqueue each event to the response stream.
 */
export async function* deployClientInstanceStream(clientId: string): AsyncGenerator<DeployEvent> {
  const [client] = await db.select().from(clients).where(eq(clients.id, clientId)).limit(1)
  if (!client) throw new Error("Client not found")
  const [config] = await db
    .select()
    .from(clientConfig)
    .where(eq(clientConfig.clientId, clientId))
    .limit(1)
  if (!config) throw new Error("Client config not found")

  const authtoken = process.env.NGROK_AUTHTOKEN
  if (!authtoken) throw new Error("NGROK_AUTHTOKEN is not configured on the dashboard")

  const slug = client.slug
  const project = `esnack-${slug}`
  const clientDir = path.join(CLIENTS_DIR, slug)
  const network = `${project}_default`

  const logs: DeployEvent[] = []
  const pushLog = (message: string) => logs.push({ type: "log", message })

  yield { type: "phase", phase: "clone", message: `Préparation de ${clientDir}` }
  await mkdir(clientDir, { recursive: true })

  if (await exists(path.join(clientDir, ".git"))) {
    yield { type: "phase", phase: "clone", message: "Repo déjà cloné — mise à jour (git fetch + reset)" }
    await runBinStream("git", ["-C", clientDir, "fetch", "origin"], { onLine: pushLog })
    while (logs.length) yield logs.shift()!
    await runBinStream("git", ["-C", clientDir, "reset", "--hard", "origin/main"], { onLine: pushLog })
    while (logs.length) yield logs.shift()!
  } else {
    yield { type: "phase", phase: "clone", message: `Clonage de ${ESNACK_REPO}` }
    // Stream each progress line from git as it arrives
    const clonePromise = runBinStream(
      "git",
      ["clone", "--depth", "1", "--progress", ESNACK_REPO, clientDir],
      { onLine: pushLog }
    )
    yield* pollLogs(logs, clonePromise)
  }

  yield { type: "phase", phase: "config", message: "Génération du .env depuis client_config" }
  // Use a placeholder URL initially — we'll overwrite .env with the real
  // ngrok URL and recreate api+frontend once the tunnel is up.
  const placeholderUrl = `http://localhost`
  await writeFile(path.join(clientDir, ".env"), buildEnvFile(client, config, placeholderUrl))
  await writeFile(path.join(clientDir, "docker-compose.override.yml"), buildOverrideCompose())
  yield { type: "log", message: ".env et docker-compose.override.yml écrits" }

  yield { type: "phase", phase: "build", message: "Build + démarrage de la stack (docker compose up --build)" }
  const upPromise = runBinStream(
    "docker",
    ["compose", "-p", project, "up", "-d", "--build"],
    { cwd: clientDir, onLine: pushLog }
  )
  yield* pollLogs(logs, upPromise)

  yield { type: "phase", phase: "ngrok", message: "Lancement du tunnel ngrok" }
  const ngrokName = `${project}-ngrok`
  await stopAndRemoveIfExists(ngrokName)

  const docker = getDocker()
  const ngrok = await docker.createContainer({
    name: ngrokName,
    Image: "ngrok/ngrok:latest",
    Cmd: ["http", "frontend:3000", "--log=stdout"],
    Env: [`NGROK_AUTHTOKEN=${authtoken}`],
    Labels: {
      [MANAGED_LABEL]: "true",
      "klinkragency.client_id": client.id,
      "klinkragency.client_slug": client.slug,
      "klinkragency.role": "ngrok",
    },
    HostConfig: {
      NetworkMode: network,
      RestartPolicy: { Name: "unless-stopped" },
    },
    ExposedPorts: { "4040/tcp": {} },
  })
  await ngrok.start()
  yield { type: "log", message: `Container ${ngrokName} démarré` }

  yield { type: "phase", phase: "tunnel", message: "Attente de l'URL publique ngrok" }
  const publicUrl = await waitForNgrokUrl(ngrokName)
  yield { type: "log", message: `URL obtenue : ${publicUrl}` }

  // Rewrite .env with the real URL and recreate api+frontend so they read it
  yield { type: "phase", phase: "finalize", message: "Injection de PUBLIC_URL + recréation api/frontend" }
  await writeFile(path.join(clientDir, ".env"), buildEnvFile(client, config, publicUrl))
  const recreatePromise = runBinStream(
    "docker",
    ["compose", "-p", project, "up", "-d", "--force-recreate", "api", "frontend"],
    { cwd: clientDir, onLine: pushLog }
  )
  yield* pollLogs(logs, recreatePromise)

  await db
    .update(clients)
    .set({
      publicUrl,
      composeProject: project,
      ngrokContainerId: ngrok.id,
      status: "deployed",
      deployedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(clients.id, clientId))

  await recordProjectContainersInDb(project, client.id)

  yield { type: "done", publicUrl, composeProject: project }
}

/** Polls the logs buffer while a promise is pending, yielding events as they appear. */
async function* pollLogs(
  logs: DeployEvent[],
  promise: Promise<unknown>
): AsyncGenerator<DeployEvent> {
  let settled = false
  let error: Error | null = null
  promise.then(() => { settled = true }).catch((e) => { error = e instanceof Error ? e : new Error(String(e)); settled = true })
  while (!settled) {
    while (logs.length) yield logs.shift()!
    await new Promise((r) => setTimeout(r, 50))
  }
  while (logs.length) yield logs.shift()!
  if (error) throw error
}

/** Non-streaming stop for symmetry with the POST endpoint. Fast enough to be synchronous. */
export async function stopClientInstance(clientId: string): Promise<void> {
  const [client] = await db.select().from(clients).where(eq(clients.id, clientId)).limit(1)
  if (!client) throw new Error("Client not found")
  if (!client.composeProject) return

  const clientDir = path.join(CLIENTS_DIR, client.slug)
  await stopAndRemoveIfExists(`${client.composeProject}-ngrok`)

  if (await exists(path.join(clientDir, "docker-compose.yml"))) {
    try {
      await runBinStream(
        "docker",
        [
          "compose",
          "-p",
          client.composeProject,
          "down",
          "-v",
          "--remove-orphans",
        ],
        { cwd: clientDir, onLine: () => {} }
      )
    } catch (err) {
      console.warn("compose down failed, continuing:", err)
    }
  }

  try {
    await rm(clientDir, { recursive: true, force: true })
  } catch {}

  await db.delete(managedContainers).where(eq(managedContainers.clientId, clientId))
  await db
    .update(clients)
    .set({
      publicUrl: null,
      composeProject: null,
      ngrokContainerId: null,
      status: "provisioned",
      updatedAt: new Date(),
    })
    .where(eq(clients.id, clientId))
}

async function stopAndRemoveIfExists(containerName: string): Promise<void> {
  const docker = getDocker()
  try {
    await docker.getContainer(containerName).remove({ force: true })
  } catch {
    // Not running / doesn't exist, ignore
  }
}

async function recordProjectContainersInDb(project: string, clientId: string): Promise<void> {
  const docker = getDocker()
  const list = await docker.listContainers({
    all: true,
    filters: { label: [`com.docker.compose.project=${project}`] },
  })
  for (const c of list) {
    const name = c.Names[0]?.replace(/^\//, "") ?? c.Id.slice(0, 12)
    try {
      await db
        .insert(managedContainers)
        .values({
          dockerName: name,
          image: c.Image,
          clientId,
        })
        .onConflictDoNothing()
    } catch {}
  }
}

async function waitForNgrokUrl(ngrokContainerName: string, timeoutMs = 20000): Promise<string> {
  const docker = getDocker()
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    try {
      const execHandle = await docker
        .getContainer(ngrokContainerName)
        .exec({
          Cmd: ["wget", "-qO-", "http://127.0.0.1:4040/api/tunnels"],
          AttachStdout: true,
          AttachStderr: true,
        })
      const stream = await execHandle.start({ hijack: true, stdin: false })
      const body = await collectStream(stream)
      const json = extractJson(body)
      if (json) {
        const parsed = JSON.parse(json) as { tunnels?: { public_url?: string }[] }
        const url = parsed.tunnels?.[0]?.public_url
        if (url) return url
      }
    } catch {}
    await new Promise((r) => setTimeout(r, 1000))
  }
  throw new Error("Timed out waiting for ngrok public URL (check NGROK_AUTHTOKEN)")
}

function collectStream(stream: NodeJS.ReadableStream): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    stream.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)))
    stream.on("end", () => resolve(Buffer.concat(chunks)))
    stream.on("error", reject)
  })
}

function extractJson(buf: Buffer): string | null {
  let text = ""
  let i = 0
  while (i < buf.length) {
    if (i + 8 > buf.length) break
    const size = buf.readUInt32BE(i + 4)
    i += 8
    const end = Math.min(i + size, buf.length)
    text += buf.toString("utf8", i, end)
    i = end
  }
  if (!text) text = buf.toString("utf8")
  const jsonStart = text.indexOf("{")
  return jsonStart >= 0 ? text.slice(jsonStart) : null
}
