import { spawn as spawnProcess } from "node:child_process"
import { writeFile, mkdir, rm, access } from "node:fs/promises"
import path from "node:path"
import { eq } from "drizzle-orm"
import { db, clients, clientConfig, managedContainers } from "@/lib/db"
import { getDocker } from "@/lib/docker"
import { upsertClientSite, removeClientSite, publicUrlForSlug } from "@/lib/caddy"
import type { Client, ClientConfig } from "@/lib/db/schema"

const CLIENTS_DIR = process.env.CLIENTS_DIR || "/srv/clients"
const ESNACK_REPO = "https://github.com/klinkragency/e-snack.git"

export type DeployEvent =
  | { type: "phase"; phase: string; message: string }
  | { type: "log"; message: string }
  | { type: "error"; message: string }
  | { type: "done"; publicUrl: string; composeProject: string }

/** Runs a binary (no shell, no injection risk), streaming each stdout/stderr line via onLine. */
function runBinStream(
  cmd: string,
  args: string[],
  opts: { cwd?: string; env?: Record<string, string>; onLine: (line: string) => void } = { onLine: () => {} }
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawnProcess(cmd, args, {
      cwd: opts.cwd,
      env: { ...process.env, ...opts.env },
      shell: false,
    })
    let stderrTail = ""
    const emit = (buf: Buffer | string) => {
      buf.toString().split("\n").forEach((l) => {
        if (l.length > 0) opts.onLine(l)
      })
    }
    child.stdout?.on("data", emit)
    child.stderr?.on("data", (b: Buffer) => {
      stderrTail += b.toString()
      emit(b)
    })
    child.on("error", reject)
    child.on("close", (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${cmd} exit ${code}: ${stderrTail.slice(-400)}`))
    })
  })
}

function buildEnvFile(client: Client, config: ClientConfig, publicUrl: string): string {
  return [
    `# Generated by Klinkragency Dashboard at ${new Date().toISOString()}`,
    `DOMAIN=${new URL(publicUrl).hostname}`,
    `PUBLIC_URL=${publicUrl}`,
    `ALLOWED_ORIGIN=${publicUrl}`,
    `COOKIE_DOMAIN=`,
    `POSTGRES_USER=esnack`,
    `POSTGRES_PASSWORD=${config.postgresPassword}`,
    `POSTGRES_DB=esnack_db`,
    `JWT_SECRET=${config.jwtSecret}`,
    `COOKIE_SECRET=${config.cookieSecret}`,
    `BACKEND_URL=http://api:8080`,
    `INITIAL_ADMIN_EMAIL=${config.initialAdminEmail}`,
    `INITIAL_ADMIN_PASSWORD=${config.initialAdminPassword}`,
    `INITIAL_ADMIN_NAME=${config.initialAdminName}`,
    `INITIAL_RESTAURANT_NAME=${config.initialRestaurantName}`,
    `INITIAL_RESTAURANT_SLUG=${config.initialRestaurantSlug}`,
    `EMAIL_FROM_ADDRESS=${config.emailFromAddress}`,
    `EMAIL_FROM=${config.emailFromAddress}`,
    `EMAIL_FROM_NAME=${client.name}`,
    `EMAIL_PROVIDER=resend`,
    `EMAIL_API_KEY=${config.resendApiKey ?? ""}`,
    `RESEND_API_KEY=${config.resendApiKey ?? ""}`,
    `MOLLIE_API_KEY=${config.mollieApiKey ?? ""}`,
    `MINIO_ENDPOINT=`,
    `MINIO_ACCESS_KEY=`,
    `MINIO_SECRET_KEY=`,
    `MINIO_BUCKET=uploads`,
    `MINIO_USE_SSL=false`,
    `MINIO_PUBLIC_URL=`,
    `MINIO_ROOT_USER=minio`,
    `MINIO_ROOT_PASSWORD=${config.minioRootPassword}`,
    `GOOGLE_CLIENT_ID=`,
    `NEXT_PUBLIC_GOOGLE_CLIENT_ID=`,
    `OPENAI_API_KEY=`,
    `NEXT_PUBLIC_POSTHOG_KEY=`,
    `NEXT_PUBLIC_POSTHOG_HOST=`,
    `POSTHOG_PERSONAL_API_KEY=`,
    `POSTHOG_PROJECT_ID=`,
    `NEXT_PUBLIC_GOOGLE_OAUTH_ENABLED=false`,
    `NEXT_PUBLIC_APPLE_OAUTH_ENABLED=false`,
    `NEXT_PUBLIC_AI_IMPORT_ENABLED=false`,
    ``,
  ].join("\n")
}

/**
 * Surgical overrides to e-snack's upstream compose:
 * - unbinds postgres host port (would collide with dashboard's own pg)
 * - hides caddy behind a never-enabled profile (we use the VPS Caddy)
 * - binds frontend to a random localhost port so the VPS Caddy can
 *   reverse-proxy to it without conflict between multiple clients
 */
function buildOverrideCompose(): string {
  return [
    "services:",
    "  postgres:",
    "    ports: !reset []",
    "  caddy:",
    '    profiles: ["disabled-by-dashboard"]',
    "  frontend:",
    "    ports:",
    '      - "127.0.0.1::3000"',
    "",
  ].join("\n")
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

/** Deploys a client instance, streaming progress events. Returns `<slug>.panelcrapuleux.fr`. */
export async function* deployClientInstanceStream(clientId: string): AsyncGenerator<DeployEvent> {
  const [client] = await db.select().from(clients).where(eq(clients.id, clientId)).limit(1)
  if (!client) throw new Error("Client not found")
  const [config] = await db
    .select()
    .from(clientConfig)
    .where(eq(clientConfig.clientId, clientId))
    .limit(1)
  if (!config) throw new Error("Client config not found")

  if (config.initialAdminPassword.length < 12) {
    throw new Error(
      "Le mot de passe admin restaurant doit faire au moins 12 caractères pour qu'e-snack démarre en prod. Modifie-le dans la fiche client et réessaie."
    )
  }

  const slug = client.slug
  const project = `esnack-${slug}`
  const clientDir = path.join(CLIENTS_DIR, slug)
  const publicUrl = publicUrlForSlug(slug)

  const logs: DeployEvent[] = []
  const pushLog = (message: string) => logs.push({ type: "log", message })

  yield { type: "phase", phase: "prepare", message: `URL publique planifiée : ${publicUrl}` }

  // Auto-cleanup any residue from a previous failed attempt
  const cleanupCount = await forceCleanupProject(project)
  if (cleanupCount > 0) {
    yield { type: "log", message: `Nettoyage: ${cleanupCount} ressource(s) résiduelle(s) supprimée(s)` }
  }

  await mkdir(clientDir, { recursive: true })

  if (await exists(path.join(clientDir, ".git"))) {
    yield { type: "phase", phase: "clone", message: "Repo déjà cloné — mise à jour (git fetch + reset)" }
    await runBinStream("git", ["-C", clientDir, "fetch", "origin"], { onLine: pushLog })
    while (logs.length) yield logs.shift()!
    await runBinStream("git", ["-C", clientDir, "reset", "--hard", "origin/main"], { onLine: pushLog })
    while (logs.length) yield logs.shift()!
  } else {
    yield { type: "phase", phase: "clone", message: `Clonage de ${ESNACK_REPO}` }
    const clonePromise = runBinStream(
      "git",
      ["clone", "--depth", "1", "--progress", ESNACK_REPO, clientDir],
      { onLine: pushLog }
    )
    yield* pollLogs(logs, clonePromise)
  }

  yield { type: "phase", phase: "config", message: "Génération du .env avec l'URL publique finale" }
  await writeFile(path.join(clientDir, ".env"), buildEnvFile(client, config, publicUrl))
  await writeFile(path.join(clientDir, "docker-compose.override.yml"), buildOverrideCompose())
  yield { type: "log", message: ".env et docker-compose.override.yml écrits" }

  yield { type: "phase", phase: "build", message: "Build + démarrage de la stack (docker compose up --build)" }
  const upPromise = runBinStream(
    "docker",
    ["compose", "-p", project, "up", "-d", "--build"],
    { cwd: clientDir, onLine: pushLog }
  )
  yield* pollLogs(logs, upPromise)

  yield { type: "phase", phase: "route", message: "Configuration Caddy + obtention du certificat TLS" }
  const hostPort = await getFrontendHostPort(project)
  yield { type: "log", message: `Frontend exposé sur 127.0.0.1:${hostPort}` }

  await upsertClientSite(slug, hostPort)
  yield { type: "log", message: `Caddy reloadé, vhost ${slug}.${new URL(publicUrl).hostname.split(".").slice(1).join(".")} actif` }

  await db
    .update(clients)
    .set({
      publicUrl,
      composeProject: project,
      ngrokContainerId: null,
      status: "deployed",
      deployedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(clients.id, clientId))

  await recordProjectContainersInDb(project, client.id)

  yield { type: "done", publicUrl, composeProject: project }
}

async function* pollLogs(
  logs: DeployEvent[],
  promise: Promise<unknown>
): AsyncGenerator<DeployEvent> {
  let settled = false
  let error: Error | null = null
  promise
    .then(() => { settled = true })
    .catch((e) => { error = e instanceof Error ? e : new Error(String(e)); settled = true })
  while (!settled) {
    while (logs.length) yield logs.shift()!
    await new Promise((r) => setTimeout(r, 50))
  }
  while (logs.length) yield logs.shift()!
  if (error) throw error
}

/** Tears down a client's stack + removes its Caddy vhost + local working dir. */
export async function stopClientInstance(clientId: string): Promise<void> {
  const [client] = await db.select().from(clients).where(eq(clients.id, clientId)).limit(1)
  if (!client) throw new Error("Client not found")

  const project = client.composeProject || `esnack-${client.slug}`
  const clientDir = path.join(CLIENTS_DIR, client.slug)

  // Remove Caddy vhost first so the domain stops routing to the about-to-die stack
  try {
    await removeClientSite(client.slug)
  } catch (err) {
    console.warn("Caddy site removal failed, continuing:", err)
  }

  if (await exists(path.join(clientDir, "docker-compose.yml"))) {
    try {
      await runBinStream(
        "docker",
        ["compose", "-p", project, "down", "-v", "--remove-orphans"],
        { cwd: clientDir, onLine: () => {} }
      )
    } catch (err) {
      console.warn("compose down failed, falling back to force cleanup:", err)
    }
  }

  await forceCleanupProject(project)

  try {
    await rm(clientDir, { recursive: true, force: true })
  } catch {}

  await db.delete(managedContainers).where(eq(managedContainers.clientId, clientId))
  await db
    .update(clients)
    .set({
      publicUrl: null,
      composeProject: null,
      ngrokContainerId: null,
      status: "provisioned",
      updatedAt: new Date(),
    })
    .where(eq(clients.id, clientId))
}

/**
 * Force-removes every container / network / volume for a compose project.
 * Also removes the Caddy vhost file if it exists (by inferring slug from
 * project name "esnack-<slug>"). Idempotent.
 */
export async function forceCleanupProject(project: string): Promise<number> {
  const docker = getDocker()
  let count = 0

  // Best-effort: remove the Caddy vhost for this project's slug
  const slug = project.startsWith("esnack-") ? project.slice("esnack-".length) : null
  if (slug) {
    try {
      await removeClientSite(slug)
    } catch {}
  }

  const containers = await docker.listContainers({
    all: true,
    filters: { label: [`com.docker.compose.project=${project}`] },
  })
  for (const c of containers) {
    try {
      await docker.getContainer(c.Id).remove({ force: true, v: true })
      count++
    } catch {}
  }

  // Legacy: old ngrok sidecar name from earlier versions
  try {
    await docker.getContainer(`${project}-ngrok`).remove({ force: true, v: true })
    count++
  } catch {}

  const networks = await docker.listNetworks({
    filters: { label: [`com.docker.compose.project=${project}`] },
  })
  for (const n of networks) {
    try {
      await docker.getNetwork(n.Id).remove()
      count++
    } catch {}
  }

  const volumes = await docker.listVolumes({
    filters: { label: [`com.docker.compose.project=${project}`] },
  })
  for (const v of volumes.Volumes || []) {
    try {
      await docker.getVolume(v.Name).remove()
      count++
    } catch {}
  }

  return count
}

async function getFrontendHostPort(project: string): Promise<number> {
  const docker = getDocker()
  const list = await docker.listContainers({
    all: true,
    filters: {
      label: [
        `com.docker.compose.project=${project}`,
        `com.docker.compose.service=frontend`,
      ],
    },
  })
  const frontend = list[0]
  if (!frontend) throw new Error("frontend container not found after compose up")
  const binding = frontend.Ports.find(
    (p) => p.PrivatePort === 3000 && p.PublicPort && p.Type === "tcp"
  )
  if (!binding?.PublicPort) {
    throw new Error("frontend container has no public port binding")
  }
  return binding.PublicPort
}

async function recordProjectContainersInDb(project: string, clientId: string): Promise<void> {
  const docker = getDocker()
  const list = await docker.listContainers({
    all: true,
    filters: { label: [`com.docker.compose.project=${project}`] },
  })
  for (const c of list) {
    const name = c.Names[0]?.replace(/^\//, "") ?? c.Id.slice(0, 12)
    try {
      await db
        .insert(managedContainers)
        .values({ dockerName: name, image: c.Image, clientId })
        .onConflictDoNothing()
    } catch {}
  }
}
