import { spawn as spawnProcess } from "node:child_process"
import { writeFile, mkdir, rm, access } from "node:fs/promises"
import path from "node:path"
import { eq } from "drizzle-orm"
import { db, clients, clientConfig, managedContainers } from "@/lib/db"
import { getDocker, MANAGED_LABEL } from "@/lib/docker"
import type { Client, ClientConfig } from "@/lib/db/schema"

const CLIENTS_DIR = process.env.CLIENTS_DIR || "/srv/clients"
const ESNACK_REPO = "https://github.com/klinkragency/e-snack.git"

/**
 * Runs a binary via spawn (no shell — args are passed as an array so no
 * command injection is possible, even if caller provides user-controlled
 * strings as args). Rejects on non-zero exit.
 */
function runBin(
  cmd: string,
  args: string[],
  opts: { cwd?: string; env?: Record<string, string> } = {}
): Promise<string> {
  return new Promise((resolve, reject) => {
    let stdout = ""
    let stderr = ""
    const child = spawnProcess(cmd, args, {
      cwd: opts.cwd,
      env: { ...process.env, ...opts.env },
      shell: false,
    })
    child.stdout?.on("data", (d) => { stdout += d.toString() })
    child.stderr?.on("data", (d) => { stderr += d.toString() })
    child.on("error", reject)
    child.on("close", (code) => {
      if (code === 0) resolve(stdout)
      else reject(new Error(`${cmd} ${args.join(" ")} failed (exit ${code}): ${stderr || stdout}`))
    })
  })
}

function buildEnvFile(client: Client, config: ClientConfig): string {
  return [
    `# Generated by Klinkragency Dashboard at ${new Date().toISOString()}`,
    `DOMAIN=localhost`,
    `PUBLIC_URL=__NGROK_URL__`,
    `POSTGRES_USER=esnack`,
    `POSTGRES_PASSWORD=${config.postgresPassword}`,
    `POSTGRES_DB=esnack_db`,
    `JWT_SECRET=${config.jwtSecret}`,
    `COOKIE_SECRET=${config.cookieSecret}`,
    `BACKEND_URL=http://api:8080`,
    `INITIAL_ADMIN_EMAIL=${config.initialAdminEmail}`,
    `INITIAL_ADMIN_PASSWORD=${config.initialAdminPassword}`,
    `INITIAL_ADMIN_NAME=${config.initialAdminName}`,
    `INITIAL_RESTAURANT_NAME=${config.initialRestaurantName}`,
    `INITIAL_RESTAURANT_SLUG=${config.initialRestaurantSlug}`,
    `EMAIL_FROM_ADDRESS=${config.emailFromAddress}`,
    `RESEND_API_KEY=${config.resendApiKey ?? ""}`,
    `MOLLIE_API_KEY=${config.mollieApiKey ?? ""}`,
    `MINIO_ROOT_USER=minio`,
    `MINIO_ROOT_PASSWORD=${config.minioRootPassword}`,
    `MINIO_BUCKET=uploads`,
    `NEXT_PUBLIC_GOOGLE_OAUTH_ENABLED=false`,
    `NEXT_PUBLIC_APPLE_OAUTH_ENABLED=false`,
    `NEXT_PUBLIC_AI_IMPORT_ENABLED=false`,
    ``,
  ].join("\n")
}

/**
 * Override compose file — unbinds every host port from the e-snack base
 * compose so multiple client stacks coexist without colliding. All services
 * stay reachable on the per-project Docker network; ngrok joins that network
 * and tunnels to the frontend via its container hostname.
 */
function buildOverrideCompose(): string {
  return [
    "services:",
    "  postgres:",
    "    ports: !reset []",
    "  api:",
    "    ports: !reset []",
    "  frontend:",
    "    ports: !reset []",
    "  minio:",
    "    ports: !reset []",
    "  caddy:",
    "    ports: !reset []",
    "",
  ].join("\n")
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

/** Starts the e-snack stack for a client. Returns the public ngrok URL. */
export async function deployClientInstance(
  clientId: string
): Promise<{ publicUrl: string; composeProject: string }> {
  const [client] = await db.select().from(clients).where(eq(clients.id, clientId)).limit(1)
  if (!client) throw new Error("Client not found")
  const [config] = await db
    .select()
    .from(clientConfig)
    .where(eq(clientConfig.clientId, clientId))
    .limit(1)
  if (!config) throw new Error("Client config not found")

  const authtoken = process.env.NGROK_AUTHTOKEN
  if (!authtoken) throw new Error("NGROK_AUTHTOKEN is not configured on the dashboard")

  const slug = client.slug
  const project = `esnack-${slug}`
  const clientDir = path.join(CLIENTS_DIR, slug)
  const network = `${project}_default`

  // 1. Ensure dir + clone or fetch
  await mkdir(clientDir, { recursive: true })
  if (await exists(path.join(clientDir, ".git"))) {
    await runBin("git", ["-C", clientDir, "fetch", "origin"])
    await runBin("git", ["-C", clientDir, "reset", "--hard", "origin/main"])
  } else {
    await runBin("git", ["clone", "--depth", "1", ESNACK_REPO, clientDir])
  }

  // 2. Write .env + override compose
  await writeFile(path.join(clientDir, ".env"), buildEnvFile(client, config))
  await writeFile(path.join(clientDir, "docker-compose.override.yml"), buildOverrideCompose())

  // 3. Boot the stack (compose reads both compose files automatically)
  await runBin(
    "docker",
    ["compose", "-p", project, "--profile", "prod", "up", "-d", "--build"],
    { cwd: clientDir }
  )

  // 4. Start ngrok sidecar joined to the client's compose network
  const ngrokName = `${project}-ngrok`
  await stopAndRemoveIfExists(ngrokName)

  const docker = getDocker()
  const ngrok = await docker.createContainer({
    name: ngrokName,
    Image: "ngrok/ngrok:latest",
    Cmd: ["http", "frontend:3000", "--log=stdout"],
    Env: [`NGROK_AUTHTOKEN=${authtoken}`],
    Labels: {
      [MANAGED_LABEL]: "true",
      "klinkragency.client_id": client.id,
      "klinkragency.client_slug": client.slug,
      "klinkragency.role": "ngrok",
    },
    HostConfig: {
      NetworkMode: network,
      RestartPolicy: { Name: "unless-stopped" },
    },
    ExposedPorts: { "4040/tcp": {} },
  })
  await ngrok.start()

  // 5. Poll ngrok's local API (inside container) for the public URL
  const publicUrl = await waitForNgrokUrl(ngrokName)

  // 6. Persist state + record all managed containers
  await db
    .update(clients)
    .set({
      publicUrl,
      composeProject: project,
      ngrokContainerId: ngrok.id,
      status: "deployed",
      deployedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(clients.id, clientId))

  await recordProjectContainersInDb(project, client.id)

  return { publicUrl, composeProject: project }
}

/** Tears down a client stack + ngrok + local working dir. */
export async function stopClientInstance(clientId: string): Promise<void> {
  const [client] = await db.select().from(clients).where(eq(clients.id, clientId)).limit(1)
  if (!client) throw new Error("Client not found")
  if (!client.composeProject) return

  const clientDir = path.join(CLIENTS_DIR, client.slug)

  await stopAndRemoveIfExists(`${client.composeProject}-ngrok`)

  if (await exists(path.join(clientDir, "docker-compose.yml"))) {
    try {
      await runBin(
        "docker",
        [
          "compose",
          "-p",
          client.composeProject,
          "--profile",
          "prod",
          "down",
          "-v",
          "--remove-orphans",
        ],
        { cwd: clientDir }
      )
    } catch (err) {
      console.warn("compose down failed, continuing:", err)
    }
  }

  try {
    await rm(clientDir, { recursive: true, force: true })
  } catch {}

  await db.delete(managedContainers).where(eq(managedContainers.clientId, clientId))
  await db
    .update(clients)
    .set({
      publicUrl: null,
      composeProject: null,
      ngrokContainerId: null,
      status: "provisioned",
      updatedAt: new Date(),
    })
    .where(eq(clients.id, clientId))
}

// ─── Helpers ────────────────────────────────────────────────────────────

async function stopAndRemoveIfExists(containerName: string): Promise<void> {
  const docker = getDocker()
  try {
    await docker.getContainer(containerName).remove({ force: true })
  } catch {
    // Not running / doesn't exist, ignore
  }
}

async function recordProjectContainersInDb(project: string, clientId: string): Promise<void> {
  const docker = getDocker()
  const list = await docker.listContainers({
    all: true,
    filters: { label: [`com.docker.compose.project=${project}`] },
  })
  for (const c of list) {
    const name = c.Names[0]?.replace(/^\//, "") ?? c.Id.slice(0, 12)
    try {
      await db
        .insert(managedContainers)
        .values({
          dockerName: name,
          image: c.Image,
          clientId,
        })
        .onConflictDoNothing()
    } catch {
      // dockerName unique — ignore on redeploy
    }
  }
}

async function waitForNgrokUrl(ngrokContainerName: string, timeoutMs = 20000): Promise<string> {
  const docker = getDocker()
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    try {
      const execHandle = await docker
        .getContainer(ngrokContainerName)
        .exec({
          Cmd: ["wget", "-qO-", "http://127.0.0.1:4040/api/tunnels"],
          AttachStdout: true,
          AttachStderr: true,
        })
      const stream = await execHandle.start({ hijack: true, stdin: false })
      const body = await collectStream(stream)
      const json = extractJson(body)
      if (json) {
        const parsed = JSON.parse(json) as { tunnels?: { public_url?: string }[] }
        const url = parsed.tunnels?.[0]?.public_url
        if (url) return url
      }
    } catch {
      // retry
    }
    await new Promise((r) => setTimeout(r, 1000))
  }
  throw new Error("Timed out waiting for ngrok public URL (check NGROK_AUTHTOKEN)")
}

function collectStream(stream: NodeJS.ReadableStream): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    stream.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)))
    stream.on("end", () => resolve(Buffer.concat(chunks)))
    stream.on("error", reject)
  })
}

function extractJson(buf: Buffer): string | null {
  let text = ""
  let i = 0
  while (i < buf.length) {
    if (i + 8 > buf.length) break
    const size = buf.readUInt32BE(i + 4)
    i += 8
    const end = Math.min(i + size, buf.length)
    text += buf.toString("utf8", i, end)
    i = end
  }
  if (!text) text = buf.toString("utf8")
  const jsonStart = text.indexOf("{")
  return jsonStart >= 0 ? text.slice(jsonStart) : null
}
